### ISSUE TITLE
basemap installation does not work on Windows 10

### ISSUE THREAD

**Issue by jgliss** [conda-forge/geonum-feedstock#6] opened 2019-05-22 12:00 UTC
Issue: Currently, the basemap installation does not work on Windows 10. I installed geonum into a new (empty) Python 3 environment and get the following error when trying to import basemap:
```
python -c "from mpl_toolkits.basemap import Basemap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonas\Anaconda3\envs\geonum\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jonas\\Anaconda3\\envs\\geonum\\Library\\share\\proj\\epsg'
```
This is addressed in PR #5 and will be fixed soon, but for now, remains a problem.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\Jonas\Anaconda3\envs\geonum:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
basemap                   1.2.0            py37h4e5d7af_0    anaconda
blas                      1.0                         mkl    anaconda
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37hb32ad35_0    conda-forge
cftime                    1.0.3.4         py37h452e1ab_1001    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cryptography              2.6.1            py37hb32ad35_0    conda-forge
curl                      7.64.1               h4496350_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
geonum                    1.4.3                      py_2    conda-forge
geos                      3.6.2             he025d50_1004    conda-forge
gpxpy                     1.3.5                      py_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1    anaconda
icu                       58.1                     vc14_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.3                      203    anaconda
jpeg                      9c                hfa6e2cd_1001    conda-forge
kiwisolver                1.1.0            py37he980bc4_0    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
latlon23                  1.0.7                      py_0    conda-forge
libblas                   3.8.0                    10_mkl    conda-forge
libcblas                  3.8.0                    10_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
liblapack                 3.8.0                    10_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
matplotlib                3.1.0                    py37_0    conda-forge
matplotlib-base           3.1.0            py37h3e3dc42_0    conda-forge
mkl                       2019.3                      203    anaconda
more-itertools            4.3.0                 py37_1000    conda-forge
netcdf4                   1.5.1.2          py37h2b7c3b1_0    conda-forge
numpy                     1.16.3           py37h873a0b8_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pluggy                    0.11.0                     py_0    conda-forge
proj4                     6.1.0                hc2d0af5_1    conda-forge
py                        1.8.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    2.1.3            py37h3f740ce_2    conda-forge
pyqt                      5.9.2            py37h6538335_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
pytest                    4.5.0                    py37_0    conda-forge
python                    3.7.3                hb12ca83_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
qt                        5.9.7                hc6833c9_1    conda-forge
requests                  2.22.0                   py37_0    conda-forge
scipy                     1.2.1            py37h29ff71c_0    anaconda
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
srtm.py                   0.3.4                      py_0    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
tornado                   6.0.2            py37hfa6e2cd_0    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : geonum
    active env location : C:\Users\Jonas\Anaconda3\envs\geonum
            shell level : 11
       user config file : C:\Users\Jonas\.condarc
 populated config files : C:\Users\Jonas\.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\Jonas\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda/win-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Jonas\Anaconda3\pkgs
                          C:\Users\Jonas\.conda\pkgs
                          C:\Users\Jonas\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Jonas\Anaconda3\envs
                          C:\Users\Jonas\.conda\envs
                          C:\Users\Jonas\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment] 2019-05-22 12:37
You are not using `strict` channel and you are mixing `basemap` from anaconda with `proj4 6.1.0`, which is incompatible with `basemap`, from `conda-forge`. See https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

**Comment by jgliss** [comment] 2019-05-22 12:52
@ocefpaf thanks! Will try that! But one question: can this be specified somehow in the recipe, i.e. so that the users do not need to worry about that? In my opinion, from a user perspective, calling `conda install -c conda-forge geonum` should be sufficient to ensure promised functionality.

**Comment by ocefpaf** [comment] 2019-05-22 12:55
> calling conda install -c conda-forge geonum should be sufficient to ensure promised functionality.

Nope. That is an illusion. The `strict` channel will be `default` one day and a feature request to make `-c <channel-name>` be a top channel with `strict` would be nice.

**Comment by jgliss** [comment] 2019-05-22 13:33
I agree, this would be nice, will be good to see the `strict` channel as `default`. Regardless, I would still prefer a solution, where I do not need to expect that the user has set her / his channel priority to strict when installing geonum, but one that works for now on all OS. Considering to try rolling back to fix basemap requirement to 1.0.7 in the recipe and see how far I get with this.

**Comment by jgliss** [comment] 2019-05-22 13:41
@ocefpaf I ran another problem, which I am a little lost with. I am still on Windows 10, fixed channel priority, here is my .condarc:

```
channels:
  - conda-forge
  - defaults
channel_priority: strict
```
and tried to install geonum into a new environment (like before):

```
conda create -n gt python=3
conda activate gt
conda install geonum
```
This results in:
```
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - geonum
Use "conda search <package> --info" to see the dependencies for each package.
```
Conda list (from gt env) outputs:
```
# packages in environment at C:\Users\Jonas\Anaconda3\envs\gt:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pip                       19.1.1                   py37_0    conda-forge
python                    3.7.3                hb12ca83_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
```

I reopen this issue for now.

**Comment by jgliss** [comment] 2019-05-22 13:52
Also tested this in a python=2.7 environment, same error...

**Comment by jgliss** [comment] 2019-05-22 14:10
When removing `channel_priority: strict` from `.condarc`, the installation "works" again. Calling `conda install geonum` creates following package plan:

```
The following NEW packages will be INSTALLED:

  asn1crypto         conda-forge/win-64::asn1crypto-0.24.0-py37_1003
  atomicwrites       conda-forge/noarch::atomicwrites-1.3.0-py_0
  attrs              conda-forge/noarch::attrs-19.1.0-py_0
  basemap            pkgs/main/win-64::basemap-1.2.0-py37h4e5d7af_0
  blas               pkgs/main/win-64::blas-1.0-mkl
  bzip2              conda-forge/win-64::bzip2-1.0.6-hfa6e2cd_1002
  cffi               conda-forge/win-64::cffi-1.12.3-py37hb32ad35_0
  cftime             conda-forge/win-64::cftime-1.0.3.4-py37h452e1ab_1001
  chardet            conda-forge/win-64::chardet-3.0.4-py37_1003
  colorama           conda-forge/noarch::colorama-0.4.1-py_0
  cryptography       conda-forge/win-64::cryptography-2.6.1-py37hb32ad35_0
  curl               conda-forge/win-64::curl-7.64.1-h4496350_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_1
  freetype           conda-forge/win-64::freetype-2.10.0-h5db478b_0
  geonum             conda-forge/noarch::geonum-1.4.3-py_2
  geos               conda-forge/win-64::geos-3.6.2-he025d50_1004
  gpxpy              conda-forge/noarch::gpxpy-1.3.5-py_0
  hdf4               conda-forge/win-64::hdf4-4.2.13-hf8e6fe8_1002
  hdf5               conda-forge/win-64::hdf5-1.10.4-nompi_hcc15c50_1106
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  icu                conda-forge/win-64::icu-58.1-vc14_0
  idna               conda-forge/win-64::idna-2.8-py37_1000
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.3-203
  jpeg               conda-forge/win-64::jpeg-9c-hfa6e2cd_1001
  kiwisolver         conda-forge/win-64::kiwisolver-1.1.0-py37he980bc4_0
  krb5               conda-forge/win-64::krb5-1.16.3-hdd46e55_1001
  latlon23           conda-forge/noarch::latlon23-1.0.7-py_0
  libblas            conda-forge/win-64::libblas-3.8.0-10_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-10_mkl
  libcurl            conda-forge/win-64::libcurl-7.64.1-h4496350_0
  liblapack          conda-forge/win-64::liblapack-3.8.0-10_mkl
  libnetcdf          conda-forge/win-64::libnetcdf-4.6.2-h396784b_1001
  libpng             conda-forge/win-64::libpng-1.6.37-h7602738_0
  libssh2            conda-forge/win-64::libssh2-1.8.2-h642c060_2
  matplotlib         conda-forge/win-64::matplotlib-3.1.0-py37_0
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.1.0-py37h3e3dc42_0
  mkl                pkgs/main/win-64::mkl-2019.3-203
  more-itertools     conda-forge/win-64::more-itertools-4.3.0-py37_1000
  netcdf4            conda-forge/win-64::netcdf4-1.5.1.2-py37h2b7c3b1_0
  numpy              conda-forge/win-64::numpy-1.16.3-py37h873a0b8_0
  pluggy             conda-forge/noarch::pluggy-0.11.0-py_0
  proj4              conda-forge/win-64::proj4-6.1.0-hc2d0af5_1
  py                 conda-forge/noarch::py-1.8.0-py_0
  pycparser          conda-forge/win-64::pycparser-2.19-py37_1
  pyopenssl          conda-forge/win-64::pyopenssl-19.0.0-py37_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyproj             conda-forge/win-64::pyproj-2.1.3-py37h3f740ce_2
  pyqt               conda-forge/win-64::pyqt-5.9.2-py37h6538335_0
  pyshp              conda-forge/noarch::pyshp-2.1.0-py_0
  pysocks            conda-forge/win-64::pysocks-1.7.0-py37_0
  pytest             conda-forge/win-64::pytest-4.5.0-py37_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  qt                 conda-forge/win-64::qt-5.9.7-hc6833c9_1
  requests           conda-forge/win-64::requests-2.22.0-py37_0
  scipy              pkgs/main/win-64::scipy-1.2.1-py37h29ff71c_0
  sip                conda-forge/win-64::sip-4.19.8-py37h6538335_1000
  six                conda-forge/win-64::six-1.12.0-py37_1000
  srtm.py            conda-forge/noarch::srtm.py-0.3.4-py_0
  tk                 conda-forge/win-64::tk-8.6.9-hfa6e2cd_1001
  tornado            conda-forge/win-64::tornado-6.0.2-py37hfa6e2cd_0
  urllib3            conda-forge/win-64::urllib3-1.24.3-py37_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.7-py_1
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py37_0
  zlib               conda-forge/win-64::zlib-1.2.11-h2fa13f4_1004
```

Seems that, among others, `basemap` would be installed via `anaconda` main channel, while `proj4, pyproj` are installed via `conda-forge` (which is causing the problems that were originally stated), i.e. where @ocefpaf pointed out that `proj4` version 6.1.0 is incompatible with `basemap` 1.2.0. 

Still no idea how to fix this.

**Comment by ocefpaf** [comment] 2019-05-22 14:47
> Still no idea how to fix this.

The `strict` option should work. I cannot debug this at the moment b/c I don't have a Windows machine but I'll give it a try later today.

**Comment by jgliss** [comment] 2019-05-22 14:50
I will try with a clean anaconda reinstall now.

**Comment by ocefpaf** [comment] 2019-05-22 16:22
I can reproduce it on my Windows machine. The problem is with `basemap` and its old dependencies (`proj4 <6` and `pyproj <2`). I'll see if I can do something...

**Comment by jgliss** [comment] 2019-05-22 16:32
Thanks a lot for your help and for testing! (I had the same problem after reinstallation, but that did not surprise too much).

**Comment by jgliss** [comment] 2019-05-23 06:51
@ocefpaf thanks for updating pyproj. Basemap install on my Windows machine works now properly without throwing the above error. However, it only works when **not** having specified `channel_priority: strict` (which is what I prefer anyways for the above mentioned reasons). In any case [conda-forge/basemap-feedstock#48](https://github.com/conda-forge/basemap-feedstock/issues/48) remains unresolved for now. Thanks again! I am closing this issue now.

**Comment by jgliss** [comment] 2019-05-23 08:46
@ocefpaf I am reopening this issue, since I was a little too fast. As I mentioned, basemap installation now works without setting channel priorities strict. Say I do this (still being on Windows):

```
conda create -n basemap python=3
conda activate basemap
conda install basemap
```

I get the following package plan:

```
  basemap            conda-forge/win-64::basemap-1.2.0-py37ha41f07c_2
  cycler             conda-forge/noarch::cycler-0.10.0-py_1
  freetype           conda-forge/win-64::freetype-2.10.0-h5db478b_0
  geos               conda-forge/win-64::geos-3.7.1-he025d50_1000
  icu                conda-forge/win-64::icu-58.1-vc14_0
  intel-openmp       anaconda/win-64::intel-openmp-2019.3-203
  jpeg               conda-forge/win-64::jpeg-9c-hfa6e2cd_1001
  kiwisolver         conda-forge/win-64::kiwisolver-1.1.0-py37he980bc4_0
  libblas            conda-forge/win-64::libblas-3.8.0-10_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-10_mkl
  liblapack          conda-forge/win-64::liblapack-3.8.0-10_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h7602738_0
  matplotlib         conda-forge/win-64::matplotlib-3.1.0-py37_0
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.1.0-py37h3e3dc42_0
  mkl                anaconda/win-64::mkl-2019.3-203
  numpy              conda-forge/win-64::numpy-1.16.3-py37h873a0b8_0
  proj4              anaconda/win-64::proj4-5.2.0-ha925a31_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyproj             conda-forge/win-64::pyproj-1.9.6-py37hfa6e2cd_1001
  pyqt               conda-forge/win-64::pyqt-5.9.2-py37h6538335_0
  pyshp              conda-forge/noarch::pyshp-2.1.0-py_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  qt                 conda-forge/win-64::qt-5.9.7-hc6833c9_1
  sip                conda-forge/win-64::sip-4.19.8-py37h6538335_1000
  six                conda-forge/win-64::six-1.12.0-py37_1000
  tornado            conda-forge/win-64::tornado-6.0.2-py37hfa6e2cd_0
  zlib               conda-forge/win-64::zlib-1.2.11-h2fa13f4_1004
```

If I install this, `python -c "from mpl_toolkits.basemap import Basemap"` works fine. If I subsequently install geonum into the same environment, basemap and geonum work fine.

However, if I install geonum directly into an empty enironment

```
conda create -n geonum python=3
conda activate geonum
conda install geonum
```

I get the following package plan:

```
  asn1crypto         conda-forge/win-64::asn1crypto-0.24.0-py37_1003
  atomicwrites       conda-forge/noarch::atomicwrites-1.3.0-py_0
  attrs              conda-forge/noarch::attrs-19.1.0-py_0
  basemap            anaconda/win-64::basemap-1.2.0-py37h4e5d7af_0
  blas               anaconda/win-64::blas-1.0-mkl
  bzip2              conda-forge/win-64::bzip2-1.0.6-hfa6e2cd_1002
  cffi               conda-forge/win-64::cffi-1.12.3-py37hb32ad35_0
  cftime             conda-forge/win-64::cftime-1.0.3.4-py37h452e1ab_1001
  chardet            conda-forge/win-64::chardet-3.0.4-py37_1003
  colorama           conda-forge/noarch::colorama-0.4.1-py_0
  cryptography       conda-forge/win-64::cryptography-2.6.1-py37hb32ad35_0
  curl               conda-forge/win-64::curl-7.64.1-h4496350_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_1
  freetype           conda-forge/win-64::freetype-2.10.0-h5db478b_0
  geonum             conda-forge/noarch::geonum-1.4.3-py_3
  geos               conda-forge/win-64::geos-3.6.2-he025d50_1004
  gpxpy              conda-forge/noarch::gpxpy-1.3.5-py_0
  hdf4               conda-forge/win-64::hdf4-4.2.13-hf8e6fe8_1002
  hdf5               conda-forge/win-64::hdf5-1.10.4-nompi_hcc15c50_1106
  icc_rt             anaconda/win-64::icc_rt-2019.0.0-h0cc432a_1
  icu                conda-forge/win-64::icu-58.1-vc14_0
  idna               conda-forge/win-64::idna-2.8-py37_1000
  intel-openmp       anaconda/win-64::intel-openmp-2019.3-203
  jpeg               conda-forge/win-64::jpeg-9c-hfa6e2cd_1001
  kiwisolver         conda-forge/win-64::kiwisolver-1.1.0-py37he980bc4_0
  krb5               conda-forge/win-64::krb5-1.16.3-hdd46e55_1001
  latlon23           conda-forge/noarch::latlon23-1.0.7-py_0
  libblas            conda-forge/win-64::libblas-3.8.0-10_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-10_mkl
  libcurl            conda-forge/win-64::libcurl-7.64.1-h4496350_0
  liblapack          conda-forge/win-64::liblapack-3.8.0-10_mkl
  libnetcdf          conda-forge/win-64::libnetcdf-4.6.2-h396784b_1001
  libpng             conda-forge/win-64::libpng-1.6.37-h7602738_0
  libssh2            conda-forge/win-64::libssh2-1.8.2-h642c060_2
  matplotlib         conda-forge/win-64::matplotlib-3.1.0-py37_0
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.1.0-py37h3e3dc42_0
  mkl                anaconda/win-64::mkl-2019.3-203
  more-itertools     conda-forge/win-64::more-itertools-4.3.0-py37_1000
  netcdf4            conda-forge/win-64::netcdf4-1.5.1.2-py37h2b7c3b1_0
  numpy              conda-forge/win-64::numpy-1.16.3-py37h873a0b8_0
  pluggy             conda-forge/noarch::pluggy-0.11.0-py_0
  proj4              conda-forge/win-64::proj4-6.1.0-hc2d0af5_1
  py                 conda-forge/noarch::py-1.8.0-py_0
  pycparser          conda-forge/win-64::pycparser-2.19-py37_1
  pyopenssl          conda-forge/win-64::pyopenssl-19.0.0-py37_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyproj             conda-forge/win-64::pyproj-2.1.3-py37h3f740ce_2
  pyqt               conda-forge/win-64::pyqt-5.9.2-py37h6538335_0
  pyshp              conda-forge/noarch::pyshp-2.1.0-py_0
  pysocks            conda-forge/win-64::pysocks-1.7.0-py37_0
  pytest             conda-forge/win-64::pytest-4.5.0-py37_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  qt                 conda-forge/win-64::qt-5.9.7-hc6833c9_1
  requests           conda-forge/win-64::requests-2.22.0-py37_0
  scipy              anaconda/win-64::scipy-1.2.1-py37h29ff71c_0
  sip                conda-forge/win-64::sip-4.19.8-py37h6538335_1000
  six                conda-forge/win-64::six-1.12.0-py37_1000
  srtm.py            conda-forge/noarch::srtm.py-0.3.4-py_0
  tk                 conda-forge/win-64::tk-8.6.9-hfa6e2cd_1001
  tornado            conda-forge/win-64::tornado-6.0.2-py37hfa6e2cd_0
  urllib3            conda-forge/win-64::urllib3-1.24.3-py37_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.7-py_1
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py37_0
  zlib               conda-forge/win-64::zlib-1.2.11-h2fa13f4_1004
```

If you compare with above, now `proj4=6.1.0` gets installed again and `basemap` from `anaconda` instead of `conda-forge`. When installing, this reproduces the initial error:

```
python -c "from mpl_toolkits.basemap import Basemap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonas\Anaconda3\envs\geonum\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jonas\\Anaconda3\\envs\\geonum\\Library\\share\\proj\\epsg'
```

Any ideas, how this could be fixed? Maybe fixing pyproj and proj4 versions in the recipe?

**Comment by jgliss** [comment] 2019-05-23 09:48
Seems like latest [proj4 build](https://anaconda.org/conda-forge/proj4/files) for v5.2.0 only built linux and osx but skipped windows. Maybe, if windows build in main label for v5.2.0 would be available, the above installation of geonum would not jump to anaconda channel when selecting from where to install basemap?

**Comment by ocefpaf** [comment] 2019-05-23 13:52
`strict` should get the `5.2.0` from `defaults` in that case. Maybe we have a package with bad metadata somewhere or you just found a bug in the `strict` implementation.

Anyways, I added the `proj4 5.2.0` (not sure why that failed on master while it passed on the PR when it was merged). Can you test it again?

**Comment by jgliss** [comment] 2019-05-23 14:33
Thanks for updating the package. I tested it, and I think we are getting closer ;)
Again:

```
conda create -n geonum python=3
conda activate geonum
conda install geonum
```

It now installs all `proj4, pyproj, basemap` from `conda-forge` and I end up with the following package list:

```
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
basemap                   1.2.0            py37ha41f07c_2    conda-forge
blas                      1.0                         mkl    anaconda
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37hb32ad35_0    conda-forge
cftime                    1.0.3.4         py37h452e1ab_1001    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cryptography              2.6.1            py37hb32ad35_0    conda-forge
curl                      7.64.1               h4496350_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
geonum                    1.4.3                      py_3    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
gpxpy                     1.3.5                      py_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1    anaconda
icu                       58.1                     vc14_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.3                      203    anaconda
jpeg                      9c                hfa6e2cd_1001    conda-forge
kiwisolver                1.1.0            py37he980bc4_0    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
latlon23                  1.0.7                      py_0    conda-forge
libblas                   3.8.0                    10_mkl    conda-forge
libcblas                  3.8.0                    10_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
liblapack                 3.8.0                    10_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
matplotlib                3.1.0                    py37_0    conda-forge
matplotlib-base           3.1.0            py37h3e3dc42_0    conda-forge
mkl                       2019.3                      203    anaconda
more-itertools            4.3.0                 py37_1000    conda-forge
netcdf4                   1.5.1.2          py37h2b7c3b1_0    conda-forge
numpy                     1.16.3           py37h873a0b8_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pluggy                    0.11.0                     py_0    conda-forge
proj4                     5.2.0             h6538335_1002    conda-forge
py                        1.8.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py37hfa6e2cd_1001    conda-forge
pyqt                      5.9.2            py37h6538335_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
pytest                    4.5.0                    py37_0    conda-forge
python                    3.7.3                hb12ca83_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
qt                        5.9.7                hc6833c9_1    conda-forge
requests                  2.22.0                   py37_0    conda-forge
scipy                     1.2.1            py37h29ff71c_0    anaconda
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               hfa6e2cd_0    conda-forge
srtm.py                   0.3.4                      py_0    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
tornado                   6.0.2            py37hfa6e2cd_0    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```

However, unfortunately, importing basemap throws the same error:

```
(geonum) C:\Users\Jonas\Jonas\repos\timelapse_tools>python -c "from mpl_toolkits.basemap import Basemap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jonas\Anaconda3\envs\geonum\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jonas\\Anaconda3\\envs\\geonum\\Library\\share\\proj\\epsg'
```

I checked the missing file location that caused the error `C:\\Users\\Jonas\\Anaconda3\\envs\\geonum\\Library\\share\\proj\\epsg` and found that the file `epsg` (and apparently all other files shipped with proj4) end up directly in folder `..\\Library\\share` and that there is no subdir `proj4`. I guess this is a bug in the `proj4` distribution?

**Comment by jgliss** [comment] 2019-05-23 14:45
Just quickly  checked the direct basemap installation again using `conda create -n basemap python=3 basemap`. As expected, this one is broken now as well with the new proj4 v5.2.0 from conda-forge (`py37hfa6e2cd_1001`). Before, with `anaconda/win-64::proj4-5.2.0-ha925a31_1` it worked (see post above), so my feeling is, that there is something wrong with `py37hfa6e2cd_1001`.

**Comment by ocefpaf** [comment] 2019-05-26 18:23
I just add a working version od `proj.4 5.2.0` (https://github.com/conda-forge/proj.4-feedstock/pull/48) and rebuilt `pyproj 1.9.6` with it (https://github.com/conda-forge/pyproj-feedstock/pull/41). That helps to install it without `strict` on Windows. With `strict` things are a little more complicated at the moment. I rebuilt matplotlib with the new `numpy` pinning (https://github.com/conda-forge/matplotlib-feedstock/pull/209) and am using only `matplotlib-base` as a dependency on `basemap` (https://github.com/conda-forge/basemap-feedstock/pull/49). That will make `strict` work as long as you are not installing the `qt` backend. (There are some major rebuilds needed to get the `qt`/`pyqt` stack working with `strict` on Windows that won't happen anytime soon.)

This was a lot of work to get `basemap` working on Windows and I probably will not do that again for a deprecated package. I believe it is easier to move `geonum` to `cartopy`.

**Closed as completed by ocefpaf** 2019-05-26 18:23 UTC
Labels: bug, help wanted

**Comment by jgliss** [comment] 2019-05-27 07:12
Thanks for your efforts. I absolutely agree that moving to `cartopy` is the better choice and I will make it my priority for `geonum`.

**Comment by ocefpaf** [comment] 2019-05-27 14:14
Please let me know if you can test this and if it is working. Like I mentioned above you won't get it working with anything that requires `qt`, but it should work for plots with any other mpl backend and jupyter notebooks.

PS: here is how to create a jupyter/matplotlib environment without `qt`:

```shell
conda create --name NOQT notebook jupyter_console nbconvert ipykernel ipywidgets matplotlib-base
```

**Comment by jgliss** [comment] 2019-05-27 19:37
I tested the `geonum` installation today both on Windows and Linux using `channel_priority: strict` in *.condarc*.  Everything works smoothly now! Thanks again!!
